// Cross-reference matrix of key VERIFIED measurements (generated; supports rule synthesis).
// Usage: node scripts/corpus-matrix.ts [--split extraction|validation] > datasets/corpus-matrix.<split>.md
import { existsSync } from 'node:fs';
import { abs, readJson, readYaml } from './lib/io.ts';

type Ref = { id: string; name: string; split: string; dimensions: any; pages: Array<{ id: string }> };

const get = (obs: Map<string, any>, id: string) => obs.get(id)?.value;
const q = (v: any) => (v && typeof v === 'object' && 'median' in v ? v.median : v);
const fmt = (v: any) => (v === undefined || v === null ? '—' : typeof v === 'number' ? String(Math.round(v * 100) / 100) : typeof v === 'object' ? JSON.stringify(v).slice(0, 60) : String(v));

export function matrix(split: string) {
  const corpus = readYaml<{ references: Ref[] }>(abs('datasets/corpus.yaml'));
  const rows: string[][] = [];
  const header = ['ref', 'page', 'goal', 'density', 'motion*', 'scale 390', 'scale 1440', 'display px 390→1440', 'disp vw 1440', 'body px', 'cpl 1440', 'container 1440/1920', 'families', 'transition ms', 'running anim', 'RM rules/js', 'low-contrast', 'axe crit/ser 1440', 'focus', 'MB 390', 'long tasks 1440', 'CLS pre', 'webgl', 'effects (grad/blur/glow/r24)'];
  for (const r of corpus.references.filter((x) => x.split === split)) {
    const p = abs('datasets/observations', r.id, 'verified.json');
    if (!existsSync(p)) continue;
    const obs = new Map(readJson<{ observations: any[] }>(p).observations.map((o) => [o.id, o]));
    for (const page of r.pages) {
      const k = (cat: string, vp: string, slug: string) => get(obs, `${r.id}.${cat}.${page.id}-${vp}-${slug}`);
      if (k('typography', '1440', 'body-size') === undefined && k('typography', '390', 'body-size') === undefined) continue;
      const curve = k('responsive', 'xvp', 'display-size-curve') ?? {};
      const cont = k('responsive', 'xvp', 'container-curve') ?? {};
      const fam = k('typography', '1440', 'family-share') ?? {};
      const axe = k('accessibility', '1440', 'axe-by-impact') ?? {};
      const rm = k('motion', '1440', 'reduced-motion-response') ?? {};
      const eff = k('components', '1440', 'effects') ?? {};
      const canvas = k('implementation', '1440', 'canvas-contexts') ?? {};
      rows.push([
        r.id,
        page.id,
        (r.dimensions.objectives ?? []).slice(0, 2).join('/'),
        r.dimensions.density,
        r.dimensions.motion,
        fmt(k('typography', '390', 'scale-range')),
        fmt(k('typography', '1440', 'scale-range')),
        `${fmt(curve['390x844'])}→${fmt(curve['1440x900'])}`,
        fmt(k('typography', '1440', 'display-size-vw')),
        fmt(k('typography', '1440', 'body-size')),
        fmt(q(k('typography', '1440', 'reading-chars-per-line'))),
        `${fmt(cont['1440x900'])}/${fmt(cont['1920x1080'])}`,
        String(Object.keys(fam).length),
        fmt(q(k('motion', '1440', 'transition-duration'))),
        fmt(k('motion', '1440', 'animations')?.running),
        `${fmt(rm.cssReducedMotionRules)}/${fmt(rm.jsReducedMotionQueries)}`,
        fmt(k('color', '1440', 'low-contrast-normal-share')),
        `${fmt(axe.critical ?? 0)}/${fmt(axe.serious ?? 0)}`,
        fmt(k('accessibility', '1440', 'focus-indicator-share')),
        fmt((k('performance', '390', 'transfer-bytes') ?? 0) / 1e6),
        fmt(k('performance', '1440', 'long-tasks')?.count),
        fmt(k('performance', '1440', 'cls-before-interaction')),
        Object.keys(canvas).filter((c) => /webgl/.test(c)).length ? 'yes' : 'no',
        `${fmt(eff.gradientAreaRatio)}/${fmt(eff.backdropBlurElements)}/${fmt(eff.coloredGlowShadows)}/${fmt(eff.roundedBoxShare24)}`,
      ]);
    }
  }
  const L = [`# Corpus matrix — ${split} split (generated by scripts/corpus-matrix.ts)`, '', '*motion = pre-capture judgement. All other columns are VERIFIED measurements (lab, DI environment). "—" = not measured / not applicable.', '', `| ${header.join(' | ')} |`, `|${header.map(() => '---').join('|')}|`];
  for (const row of rows) L.push(`| ${row.join(' | ')} |`);
  return L.join('\n') + '\n';
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const i = process.argv.indexOf('--split');
  process.stdout.write(matrix(i >= 0 ? process.argv[i + 1] : 'extraction'));
}
